# Generated by Django 4.0.5 on 2022-07-05 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('universityApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_address', models.TextField()),
                ('user_gender', models.CharField(max_length=255)),
                ('user_mobile', models.IntegerField()),
                ('user_photo', models.ImageField(upload_to='image/user')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='universityApp.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
