# Generated by Django 4.0.5 on 2022-07-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universityApp', '0002_usermember'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermember',
            name='user_age',
            field=models.IntegerField(null=True),
        ),
    ]
