# Generated by Django 4.0.5 on 2022-07-07 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universityApp', '0003_usermember_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermember',
            name='user_age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usermember',
            name='user_photo',
            field=models.ImageField(blank=True, null=True, upload_to='image/user'),
        ),
    ]
