# Generated by Django 4.0.5 on 2022-07-07 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universityApp', '0004_alter_usermember_user_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermember',
            name='user_photo',
            field=models.ImageField(upload_to='image/user'),
        ),
    ]
